const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless:true, args:['--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport:{ width:1440, height:1000 } });
  page.setDefaultTimeout(15000);
  const errors=[]; page.on('pageerror', e => errors.push(e.message));
  await page.route('**/__local_ai/**', route => route.fulfill({ status:200, contentType:'application/json', body:JSON.stringify({data:[]}) }));
  await page.goto('http://127.0.0.1:3001');
  await page.getByText('Start modeling', { exact:true }).click();
  await page.waitForFunction(() => !!window.modelAPI);
  await page.getByRole('button', { name:'Close quick start', exact:true }).click();
  await page.getByRole('button', { name:'AI settings', exact:true }).click();
  await page.getByText('Local server URL', { exact:true }).waitFor();
  await page.getByRole('button', { name:'Cancel', exact:true }).click();
  await page.getByRole('button', { name:'Create a room', exact:false }).click();
  assert.match(await page.locator('#ai-prompt-input').inputValue(), /5m/);
  await page.getByRole('button', { name:'Send', exact:true }).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(), /Load a local/);
  await page.getByRole('button', { name:'New chat', exact:true }).click();
  // Mock the provider transport only; execute the returned tool against the actual model.
  await page.evaluate(() => {
    const invoke = window.api.invoke.bind(window.api);
    window.__aiRequests = [];
    window.api.invoke = async (channel, args) => {
      if (channel !== 'ai:chat') return invoke(channel, args);
      window.__aiRequests.push(args);
      if (!args.tools.length) return { content:[{ type:'text', text:'Choose Rectangle (R), then click two corners.' }], stop_reason:'end_turn' };
      if (window.__aiRequests.filter(r => r.tools.length).length === 1) return { content:[{ type:'tool_use', id:'box-test', name:'execute_script', input:{ operationName:'Create test box', script:'const f = model.entities.addFace(new Geom.Point3d(0,0,0), new Geom.Point3d(3,0,0), new Geom.Point3d(3,2,0), new Geom.Point3d(0,2,0)); f.pushpull(2);' } }], stop_reason:'tool_use' };
      return { content:[{ type:'text', text:'Created a 3 × 2 × 2 meter box. You can undo the modeling operation.' }], stop_reason:'end_turn' };
    };
  });
  await page.getByRole('button', { name:'Learn', exact:true }).click();
  await page.locator('#ai-prompt-input').fill('How do I draw?');
  await page.getByRole('button', { name:'Send', exact:true }).click();
  await page.getByText('Choose Rectangle (R), then click two corners.', { exact:true }).waitFor();
  assert.equal(await page.evaluate(() => window.__aiRequests[0].tools.length), 0);
  await page.getByRole('button', { name:'Build', exact:true }).click();
  await page.locator('#ai-prompt-input').fill('Make a box');
  await page.getByRole('button', { name:'Send', exact:true }).click();
  await page.getByText('Created a 3 × 2 × 2 meter box. You can undo the modeling operation.', { exact:true }).waitFor();
  const faces = await page.evaluate(() => window.modelAPI.getAllFaces().length);
  assert.ok(faces >= 6, `Expected a box, got ${faces} faces`);
  await page.getByRole('button', { name:'Extents', exact:true }).click();
  await page.screenshot({ path:'.impeccable/review/desktop.png' });
  await page.getByRole('button', { name:'Undo last operation', exact:true }).click();
  assert.equal(await page.evaluate(() => window.modelAPI.getAllFaces().length), 1);
  await page.getByRole('button', { name:'Undo last operation', exact:true }).click();
  assert.equal(await page.evaluate(() => window.modelAPI.getAllFaces().length), 0);
  await page.getByRole('button', { name:'Redo', exact:true }).click();
  await page.getByRole('button', { name:'Redo', exact:true }).click();
  assert.ok(await page.evaluate(() => window.modelAPI.getAllFaces().length) >= 6);
  await page.getByRole('button', { name:'Show all tools', exact:false }).click();
  await page.getByTitle('Polygon (Shift+G)', { exact:true }).waitFor();
  // Arrow keys in the composer must not change or invoke modeling tools.
  const toolBefore = await page.evaluate(() => window.__debugApp.toolManager.getActiveTool()?.id);
  await page.locator('#ai-prompt-input').fill('abc');
  await page.locator('#ai-prompt-input').press('ArrowLeft');
  assert.equal(await page.evaluate(() => window.__debugApp.toolManager.getActiveTool()?.id), toolBefore);
  await page.setViewportSize({ width:700, height:850 });
  await page.screenshot({ path:'.impeccable/review/compact.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole('button', { name:'Close side panel', exact:true }).click();
  await page.getByRole('button', { name:'Quick start', exact:true }).click();
  await page.screenshot({ path:'.impeccable/review/compact-guide.png' });
  assert.deepEqual(errors, []);
  console.log('PASS: setup, missing-model recovery, prompts, Learn mode, AI geometry, undo/redo, advanced tools, keyboard isolation, compact layout.');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
