import type { BuildingArchetype, BuildingFeature } from './building-catalog';

/** Family-level concept defaults: names describe uses, not bespoke surveyed designs. */
type Family = { category:string; baseType:string; dimensions:[number,number,number,number]; roof:string; feature:BuildingFeature; names:string[] };
const family=(category:string,baseType:string,dimensions:Family['dimensions'],roof:string,feature:BuildingFeature,names:string):Family=>({category,baseType,dimensions,roof,feature,names:names.split(';').map(n=>n.trim())});
export const BUILDING_FAMILIES:Family[]=[
 family('Housing forms','house',[16,12,8,2],'gable','porch','detached house;semi detached house|semi-detached home;triplex;fourplex;patio house;split level house;log cabin;beach house;lake house;mountain cabin;earth sheltered house;passive house;prefabricated house;modular house;manufactured home;container home'),
 family('Collective housing','apartment',[36,24,21,6],'flat','balconies','cohousing building;co living residence;social housing;public housing;cooperative housing;affordable housing;serviced apartments;condominium building;maisonette building;live work building;micro apartment building;workers hostel'),
 family('Care and temporary accommodation','apartment',[32,24,12,3],'hip','canopy','assisted living residence;nursing home;care home;memory care residence;hospice;children home;orphanage;homeless shelter;emergency shelter;transitional housing;refugee accommodation;family shelter'),
 family('Lodging and tourism','apartment',[30,22,16,4],'hip','balconies','grand hotel;extended stay hotel;capsule hotel;aparthotel;bed and breakfast|b and b;guesthouse;inn;ski lodge;hunting lodge;eco lodge;pilgrim hostel;campground lodge;holiday lodge;conference hotel'),
 family('Retail specialties','civic',[18,16,6,1],'flat','shopfront','bookstore;pharmacy|chemist shop;florist shop;clothing store;shoe store;jewelry store;electronics store;hardware store;pet shop;toy store;furniture showroom;home improvement store;garden center;convenience store;duty free shop;antique shop'),
 family('Commercial services','civic',[20,16,7,2],'flat','shopfront','hair salon;barbershop;beauty salon;laundromat;dry cleaner;travel agency;real estate office;insurance office;law office;accounting office;funeral home;photo studio;printing shop;repair shop;tailor shop'),
 family('Food service','civic',[20,16,6,1],'hip','canopy','coffee shop;tea house;ice cream parlor;fast food restaurant;drive through restaurant;pizzeria;steakhouse;sushi restaurant;diner;pub;tavern;bar;canteen;cafeteria;commercial kitchen;community kitchen'),
 family('Shopping complexes','civic',[70,48,18,3],'flat','skylights','retail park;outlet mall;shopping arcade;covered bazaar;wholesale market;fish market;produce market;farmers market;auction house;trade showroom;flea market hall'),
 family('Business and finance','office',[38,28,28,7],'flat','colonnade','regional headquarters;government office;administration building;municipal office;credit union;stock exchange;trading floor building;call center;conference center;convention center;exhibition center;trade fair hall;business center'),
 family('Specialist schools','civic',[42,28,12,3],'hip','colonnade','nursery school;preschool;middle school;junior school;special education school;international school;language school;music school;dance school;drama school;culinary school;driving school;flight school;maritime academy'),
 family('University facilities','civic',[44,32,18,4],'flat','skylights','university classroom building;college building;polytechnic institute;engineering school;medical school;law school;business school;student union;campus dining hall;faculty building;university administration;seminary;theological college'),
 family('Science and research','civic',[40,28,16,3],'flat','skylights','science center;innovation center;biotechnology laboratory;chemistry laboratory;physics laboratory;robotics laboratory;materials laboratory;cleanroom facility;testing laboratory;animal research facility;marine laboratory;field research station;polar research station;space research center'),
 family('Hospital specialties','civic',[64,42,30,7],'flat','canopy','children hospital|pediatric hospital;maternity hospital;cancer hospital|oncology hospital;psychiatric hospital;teaching hospital;military hospital;infectious disease hospital;surgical hospital;eye hospital;heart hospital;emergency department;trauma center'),
 family('Outpatient health services','civic',[26,20,10,2],'flat','canopy','medical center;urgent care clinic;walk in clinic;dialysis center;diagnostic imaging center;blood bank;vaccination clinic;mental health clinic;physiotherapy clinic;fertility clinic;community health center;ambulatory surgery center;dental laboratory;public health laboratory'),
 family('Museums and collections','civic',[42,32,18,3],'hip','skylights','natural history museum;science museum;maritime museum;aviation museum;railway museum;military museum;archaeology museum;children museum;design museum;photography museum;transport museum;industrial museum;local history museum;planetarium;aquarium;archive building'),
 family('Libraries and learning','civic',[30,24,13,3],'flat','colonnade','national library;regional library;school library;law library;medical library;special collections library;digital learning center;adult education center;literacy center;training center;visitor education center'),
 family('Entertainment venues','civic',[38,28,14,2],'flat','canopy','multiplex cinema;puppet theater;black box theater;outdoor stage building;amphitheater building;comedy club;nightclub;discotheque;dance hall;ballroom;bingo hall;casino;gaming arcade;escape room venue;bowling alley'),
 family('Media and creative production','warehouse',[42,30,14,2],'flat','skylights','film studio;television studio;radio station;recording studio;sound stage;animation studio;broadcast center;newsroom building;rehearsal studio;sculpture workshop;artist studio;craft workshop;makerspace'),
 family('Government and diplomacy','civic',[44,32,22,4],'hip','colonnade','parliament building;legislative assembly;senate building;supreme court;district court;tribunal;embassy;consulate;customs house;border checkpoint;immigration office;tax office;registry office;election office'),
 family('Justice and public protection','civic',[48,36,15,3],'flat','canopy','prison;correctional facility;detention center;juvenile detention center;probation office;forensic laboratory;morgue;coroner office;coast guard station;lifeboat station;lifeguard station;disaster relief center'),
 family('Christian worship and community','civic',[28,44,26,2],'gable','spire','cathedral;basilica;abbey church;parish church;mission church;monastery;convent;friary;rectory;parsonage;parish hall;baptistery;bell tower'),
 family('Religious and ceremonial buildings','civic',[30,30,18,2],'hip','colonnade','Hindu temple;Buddhist temple;Jain temple;Sikh gurdwara|gurdwara;Shinto shrine;Taoist temple;Zoroastrian fire temple;Baha i house of worship;prayer hall;Islamic center;madrasa;meditation center;retreat center;mausoleum;crematorium;memorial hall'),
 family('Historic and ceremonial residences','civic',[52,40,24,4],'hip','colonnade','palace;manor house;chateau;stately home;royal residence;governor residence;hacienda;riadh|riad;hanok house;machiya;ryokan;fortified manor;great hall'),
 family('Historic towers and fortifications','civic',[22,22,28,4],'hip','spire','fort;fortress;citadel;keep;gatehouse;watchtower;clock tower;defensive tower;signal tower;city gate;guardhouse;historic barracks'),
 family('Wellness and leisure','civic',[34,24,10,2],'hip','skylights','spa;bathhouse;hammam;sauna building;wellness center;yoga studio;pilates studio;martial arts dojo;climbing gym;trampoline park;indoor playground;recreation center;leisure center;community swimming pool'),
 family('Sport support buildings','civic',[30,20,9,2],'flat','canopy','sports pavilion;changing room building;training academy;athlete residence;sports medicine center;golf clubhouse;tennis clubhouse;sailing clubhouse;rowing clubhouse;boathouse;ski center;mountain lift station'),
 family('Rail and road transport buildings','warehouse',[54,28,14,2],'gable','platform','rail depot;rail maintenance shed;rail control center;tram depot;tram station;light rail station;coach station;bus depot;taxi terminal;truck stop;motorway service station;toll plaza building;vehicle inspection center'),
 family('Aviation and space facilities','warehouse',[60,40,18,2],'flat','hangar_door','cargo terminal;air cargo warehouse;air traffic control tower;airport fire station;airport maintenance hangar;helicopter hangar;heliport terminal;seaplane terminal;spaceport terminal;satellite control center;rocket assembly building'),
 family('Ports and waterways','warehouse',[50,30,13,2],'flat','loading_bays','cruise terminal;port authority building;harbor office;marina office;container freight station;shipyard workshop;dry dock service building;canal lock house;pilot station;fishing harbor market;lifeboat house'),
 family('Manufacturing plants','warehouse',[70,44,15,2],'flat','loading_bays','assembly plant;automobile factory;electronics factory;textile mill;garment factory;shoe factory;furniture factory;machine shop;metal fabrication plant;foundry;steel mill;glass factory;ceramics factory;brickworks;cement works;paper mill;plastics factory;pharmaceutical factory;semiconductor fabrication plant'),
 family('Food and beverage production','warehouse',[52,34,12,2],'gable','loading_bays','brewery;distillery;winery;cider mill;dairy processing plant;cheese factory;creamery;flour mill;rice mill;sugar refinery;chocolate factory;food processing plant;fish processing plant;meat processing plant;cannery;commercial bakery;bottling plant;coffee roastery'),
 family('Storage and distribution','warehouse',[64,40,12,1],'flat','loading_bays','fulfillment center;parcel sorting center;postal sorting office;freight depot;logistics hub;bonded warehouse;self storage facility;document storage facility;furniture warehouse;timber warehouse;bulk storage building;grain warehouse;refrigerated distribution center'),
 family('Livestock and farming','warehouse',[42,22,8,1],'gable','hangar_door','dairy barn;poultry house;pig barn;sheep barn;goat barn;cattle shed;milking parlor;hatchery;apiary building;kennel building;cattery;animal shelter;veterinary teaching building;feed mill;feed storage shed'),
 family('Horticulture and rural work','warehouse',[34,18,7,1],'gable','skylights','glasshouse;conservatory;orchid house;botanical garden greenhouse;plant nursery building;vertical farm;hydroponic farm;aquaponics facility;mushroom farm;potting shed;packing shed;fruit packing house;tractor shed;agricultural workshop;irrigation pump house'),
 family('Energy and electrical infrastructure','warehouse',[48,30,15,2],'flat','chimney','thermal power plant;nuclear power station building;hydroelectric powerhouse;geothermal power plant;biomass power plant;substation building;switchgear building;battery storage building;district heating plant;boiler house;turbine hall;generator house;solar farm control building;wind farm service building'),
 family('Water waste and environmental services','warehouse',[42,28,12,2],'flat','loading_bays','sewage treatment building;wastewater pumping station;water pumping station;desalination plant;water filtration building;reservoir control house;recycling center;waste transfer station;incinerator building;composting facility;environmental monitoring station;stormwater pump house'),
 family('Telecommunications and digital services','warehouse',[36,24,14,3],'flat','loading_bays','telephone exchange;telecommunications hub;internet exchange;network operations center;edge data center;colocation facility;server building;cable landing station;satellite ground station;television transmitter building;radio transmitter building'),
 family('Vehicle services','warehouse',[30,22,8,1],'flat','loading_bays','car dealership;automotive showroom;auto repair garage;body shop;tire shop;car wash;fuel station|gas station|petrol station;electric vehicle charging station building;bus repair garage;motorcycle workshop;bicycle repair shop;vehicle rental office'),
 family('Public amenities and small structures','pavilion',[12,9,5,1],'hip','canopy','public toilet;restroom building;shower block;ticket office;information kiosk;visitor center;tourist information center;park pavilion;picnic shelter;gazebo;bandstand;security booth;caretaker cottage;cemetery office;park ranger station'),
 family('Remote and specialist accommodation','house',[18,12,7,2],'gable','porch','mountain refuge;alpine hut;wilderness lodge;expedition base;offshore accommodation building;mining camp residence;construction camp residence;fire lookout cabin;desert research lodge;island field station'),
 family('Mixed use buildings','apartment',[38,28,28,7],'flat','balconies','shop house|shophouse;retail residential building;office residential building;hotel office building;retail office building;transit oriented mixed use building;community housing hub;market apartment building;workshop residence;vertical mixed use building'),
];
export const EXTENDED_BUILDING_ARCHETYPES:BuildingArchetype[]=BUILDING_FAMILIES.flatMap(f=>f.names.map(entry=>{
 const [name,...aliases]=entry.split('|');const [width,depth,height,floors]=f.dimensions;
 return {id:name.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''),name,aliases,category:f.category,baseType:f.baseType,width,depth,height,floors,roof:f.roof,feature:f.feature,coverage:'family' as const};
}));
